### ISSUE TITLE
SSH daemon not starting

### ISSUE THREAD

**Issue by david-barbion** [open-containers-manager/cli#1]
Got this message when running `ocm start`:
```
✔ OCM started
✔ Guest additions running
✖ Starting OCM SSH daemon
Promise timed out after 60000 milliseconds
```

When I try to connect manually on ocm@localhost port 2222, it works.

I'm using nodejs v10.15.2 (Ubuntu 19.04).

Output of `ocm status`:
```
$ ocm status
✔ OCM running
✖ SSH daemon stopped
```

**Comment by david-barbion** [comment]
output of `ocm-daemon`:
```
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/ocm.daemon
starting server on  /tmp/ocm.daemon 
starting TLS server false
starting server as Unix || Windows Socket
(node:24224) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit
(node:24224) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:24224) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
## socket connection to server detected ##
dispatching event to socket  :  no-ssh 
socket disconnected false
```

and loads of
```
## socket connection to server detected ##
dispatching event to socket  :  no-ssh 
socket disconnected false
```

and finally after few seconds:
```
{ Error: All configured authentication methods failed
    at doNextAuth (/home/davidb/devel/ocm/cli/node_modules/ssh2/lib/client.js:413:17)
    at tryNextAuth (/home/davidb/devel/ocm/cli/node_modules/ssh2/lib/client.js:484:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/home/davidb/devel/ocm/cli/node_modules/ssh2/lib/client.js:597:5)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/home/davidb/devel/ocm/cli/node_modules/ssh2-streams/lib/ssh.js:3728:10)
    at SSH2Stream._transform (/home/davidb/devel/ocm/cli/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/home/davidb/devel/ocm/cli/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
  level: 'client-authentication',
  attemptNumber: 58,
  retriesLeft: -47 }
```

**Comment by david-barbion** [comment]
SSH key were not deployed.
After doing `ocm install` it now works.

The only thing I did is upgrading VirtualBox from 6.0.0 to 6.0.12.
