### ISSUE TITLE
Multiple unforward

### ISSUE THREAD

**Issue by David-Vandensteen** [open-containers-manager/cli#3]
```
$ ocm-daemon
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/ocm.daemon
starting server on  /tmp/ocm.daemon
starting TLS server false
starting server as Unix || Windows Socket
forward 8080
forward 8081
broadcasting event to all known sockets listening to  \\.\pipe\tmp-ocm.daemon  :   ready
unforward 8080
unforward 8081
unforward 8080
unforward 8081
(node:10672) UnhandledPromiseRejectionWarning: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1565:12)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:10672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10672) UnhandledPromiseRejectionWarning: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1565:12)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:10672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by tonyduburque** [comment]
Fix  in comit #858a1ed7753bafafb293ef09a56ca3ae1a88ba3a
